apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
- metadata:
    name: super-secret
    labels:
      app: webapp
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
    type: Opaque
  files:
  - ./secret.yaml
